### ISSUE TITLE
remote website editing is not working (still)

### ISSUE THREAD

**Issue by pietru2004** [lane711/sonicjs#142] opened 2022-07-30 21:07 UTC
![obraz](https://user-images.githubusercontent.com/51274570/181996063-a48d5b3e-709e-448c-95a1-7cd7a3da0c04.png)

This time I have setted variables and switched local_dev setting many times.

It still works while doing it on any port via virtual desktop connection to server

![obraz](https://user-images.githubusercontent.com/51274570/181996098-60878ee7-e0b1-4af4-9ce8-3395daa6e456.png)

Ver: Beta 0.6.0

**Comment by lane711** [comment] 2022-08-01 19:54
Sorry I'm not following what the issue is here. Can you please provide some details on what you are trying to do? Are you trying to deploy in a container?

**Comment by pietru2004** [comment] 2022-08-01 20:20
I have deployed sonicjs in container editing from server via remote desktop works while otherwise it does not

Also it is followment from this https://github.com/lane711/sonicjs/issues/130 but checked on beta 0.6.0

**Comment by lane711** [comment] 2022-08-01 21:46
is this env var set correctly?
ADMIN_DOMAIN=mywebsite.com

**Comment by pietru2004** [comment] 2022-08-01 23:24
> is this env var set correctly?
> ADMIN_DOMAIN=mywebsite.com
> 

I try to not bind it to any DNS name by providing ip adress cause I want to try it in local network without any domain

**Comment by lane711** [comment] 2022-08-02 01:38
what do you mean by "does not work"? Can you please provide some details.

You might try commenting out this domain check if you are getting a 401:
https://github.com/lane711/sonicjs/blob/main/server/services/admin.service.js#L47

**Comment by pietru2004** [comment] 2022-08-02 09:07
based on this I do not get 401 page
![obraz](https://user-images.githubusercontent.com/51274570/182337179-f9e5762d-13a8-455a-8786-41c03403416a.png)
as you could see in screenshot in first msg **NODE_ENV** is set to **dev**

As I said the error is the same as in https://github.com/lane711/sonicjs/issues/130. Request for editing instance when adding something to page gets aborted (logged from page-builder.js:678:15)

![obraz](https://user-images.githubusercontent.com/51274570/182337379-6134694f-b2fb-4630-937f-43caac8bcb49.png)

**Comment by lane711** [comment] 2022-08-02 19:45
Line 678 is the catch block - what is the exact error being output? Is the sessionID available in the function?
https://github.com/lane711/sonicjs/blob/main/server/page-builder/js/page-builder.js#L678

**Comment by pietru2004** [comment] 2022-08-02 20:03
This is how cookies look
Non browser privacy mode
![obraz](https://user-images.githubusercontent.com/51274570/182463174-e23a5fd8-cfe4-4c7f-a1c4-5ec26b16ae58.png)

Browser privacy mode
![obraz](https://user-images.githubusercontent.com/51274570/182462344-abcaeca9-58e1-4f9a-971a-a942b5a2c904.png)
It is only place with any data stored

**Comment by lane711** [comment] 2022-08-19 00:27
Hi, sorry but I am still not following what the issue is here. There are other users using Sonic in a container so I'm not sure what in your setup might be causing the issue. I would recommend debugging the issue on your side to find exactly where the issue is. 

I had asked for the error being output - can you please provide that?

**Comment by pietru2004** [comment] 2022-08-19 09:31
@lane711 I have made [full video](percraft.net/SideLoad/Videos/2022-08-19 11-14-32.mkv) on how I made my setup, also it seams now I tried that it does not save ID cookies correctly on firefox browser

**Comment by lane711** [comment] 2022-08-19 17:33
Thanks for creating a video, but the link isn't working for me...

**Comment by pietru2004** [comment] 2022-08-19 18:29
Mayby this link will work (I uploaded un listed to YT) https://youtu.be/Xsg6ZOA7kfk

**Comment by pietru2004** [comment] 2022-08-19 22:13
@lane711 also I think the ynability to edit occurs mostly in firefox - for some reason I think user ID is not saved on firefox

**Comment by lane711** [comment] 2022-08-20 03:05
I haven’t gone thru the entire video but I did notice that you are using an older version of sonic. The roles page has changed in the last month or so. Have you tried with the latest code from master?

**Comment by pietru2004** [comment] 2022-08-20 07:24
I was using latest release I gona try copy master branch

**Comment by pietru2004** [comment] 2022-08-20 08:13
I have downloaded master branch via
![obraz](https://user-images.githubusercontent.com/51274570/185735782-0c8c75e0-8888-4952-8b84-3b947e01ae69.png)
and I didn't notice any change in roles page, maybe you have forgot to merge something. Also for firefox I think it does not correctly save user ID cookie.

**Comment by pietru2004** [comment] 2022-08-21 10:32
@lane711 what branch should I download then? or just wait? (Also should I use the ping or not, I know it can be bit annoying)

**Comment by lane711** [comment] 2022-08-22 15:44
Sorry my mistake, looks like I had not updated main like I thought. It is now updated. Your roles page should now look like this:
<img width="1676" alt="Screen Shot 2022-08-22 at 8 42 10 AM" src="https://user-images.githubusercontent.com/4350219/185962657-283afd1e-d3cd-4941-9876-62fa9982e693.png">

Please let me know if your issue persists after updating from main

**Comment by pietru2004** [comment] 2022-08-22 15:59
ye I see it
![obraz](https://user-images.githubusercontent.com/51274570/185965785-019fabf2-12bd-499f-949d-5d06c807d0a2.png)
still seams user ID is not saved

**Comment by lane711** [comment] 2022-08-22 16:12
Another issue I see in your video is that you deleted a column and then tried to add content afterwards. You shouldn't be able to delete a column and then add content to a section (a bug). I am completely reworking the page builder to address this and other issues but it may be a few weeks before I am ready to release the new version.

Is there another issue that needs to be addressed in your video? If so what time does it occur at?

**Comment by lane711** [comment] 2022-08-22 16:16
btw you can go to the "/user" url to check your current user/session info
<img width="1565" alt="Screen Shot 2022-08-22 at 9 16 42 AM" src="https://user-images.githubusercontent.com/4350219/185969416-c267233a-2280-452c-a0e3-7f8d5d47d36f.png">

**Comment by pietru2004** [comment] 2022-08-22 16:20
I have this look
![obraz](https://user-images.githubusercontent.com/51274570/185969975-396f6f97-baec-4289-a1e2-ce4ea8f8bbde.png)

Should there be only cookie named `sonicjs` ?

**Comment by pietru2004** [comment] 2022-08-22 16:21
I tried adding text module
![obraz](https://user-images.githubusercontent.com/51274570/185970275-8508fe96-cc8b-4748-9800-0d5956a3dd04.png)

**Comment by lane711** [comment] 2022-08-22 16:25
your session looks correct and yes you should have a cookie called "sonicjs"

Can you edit the existing modules on the home page? Again, it might be an issue if you deleted a column on your test page. Delete the section and add a new one (start over).

**Comment by pietru2004** [comment] 2022-08-22 16:49
it was fresh install

**Comment by pietru2004** [comment] 2022-08-22 16:50
fresh error on trying to delete section - browser firefox
![obraz](https://user-images.githubusercontent.com/51274570/185975857-ecbe5ee4-b784-4e96-bfe1-472eb1a424bd.png)

**Comment by pietru2004** [comment] 2022-08-22 16:58
Also User role adding seams to work
![obraz](https://user-images.githubusercontent.com/51274570/185977227-1fbbd37b-005a-4a47-8424-070cbdec9ae5.png)

**Comment by pietru2004** [comment] 2022-08-22 17:02
I crashed Sonic Permissions page by creating permission created ping
`
(node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

(node:19) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'roles' of undefined

logging in: test@percraft.net

    at Object.exports.contentTypeGet (/app/server/services/data.service.js:341:16)

    at async /app/server/services/admin.service.js:115:22

    at /app/server/services/data.service.js:350:47

(node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

(node:19) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

(Use `node --trace-warnings ...` to show where the warning was created)

    at processTicksAndRejections (internal/process/task_queues.js:95:5)

    at runMicrotasks (<anonymous>)

    at Array.map (<anonymous>)

`

**Comment by lane711** [comment] 2022-08-22 18:10
Looks like there is a bug if you can a new ACL. I'll fix that this week. The permissions in general are still a work in progress

**Comment by pietru2004** [comment] 2022-08-22 18:20
Also if you can please try running sonicjs on docker from vm. 
And please try editing website from other vm or local pc - master host, on firefox browser cause I get problems on it. It might help you solve issue I have with unability to edit webpages on firefox.

**Comment by lane711** [comment] 2022-08-22 18:24
Does your issue only happen on VM + Firefox? Have you tried Chrome?

**Comment by pietru2004** [comment] 2022-08-22 18:25
Yes it seams on chrome last time - as in video it was not an issue, which is an issue for me as I prefer firefox cause of privacy.

Also this is schematic how I use sonicjs
![obraz](https://user-images.githubusercontent.com/51274570/185992220-64b53962-24f6-453c-83c5-8e924c73c04d.png)

**Comment by lane711** [comment] 2022-08-22 19:23
I just pushed an update that should resolve your permission page crash and ability to add a new module to a page. Please try and let me know if any of the issues persists.

**Comment by pietru2004** [comment] 2022-08-22 21:51
The https://github.com/lane711/sonicjs/commit/2f092b22b8778d85d8b8f326203d27f8435fdcab seams to work
![obraz](https://user-images.githubusercontent.com/51274570/186024867-d5ffe141-01f0-414f-979b-e8a59e96165a.png)
Also I think after submit it should go back to the ACLS form cause else this happens

![obraz](https://user-images.githubusercontent.com/51274570/186024947-106b38fa-a3e9-48d7-ab26-2cb3c536adec.png)
Bit annoying I would say but not critical

**Comment by pietru2004** [comment] 2022-08-22 21:58
@lane711 Important update - checked on chrome and page builder seams fully broken for many basic types - text, title, media, FAQ, Gallery etc.
It does not load any settings
![obraz](https://user-images.githubusercontent.com/51274570/186025859-16a94883-386f-4fcd-8c9c-d51f602ec793.png)

**Comment by pietru2004** [comment] 2022-08-22 22:11
Also this shows on firefox
![obraz](https://user-images.githubusercontent.com/51274570/186027649-07816ec0-1db6-473a-af47-a4fdd65217c0.png)

**Comment by lane711** [comment] 2022-08-23 15:36
I checked main and it is all working for me as expected. This is probably still an issue with your container. I will setup SonicJs in a container and try to reproduce and fix the issues that you are having, but will be a bit lower priority since its not a highly common use case plus there are other users deploying SonicJs in a container without issues so it could be something specific to your setup. 

<img width="1647" alt="Screen Shot 2022-08-23 at 8 32 04 AM" src="https://user-images.githubusercontent.com/4350219/186200544-16b7c876-569d-41d2-ae62-ab08aef0d41d.png">

**Comment by pietru2004** [comment] 2022-08-23 16:40
Well I used sonicjs main repo docker build script

Well I not sure why one form loads components other not

Text Get this in form script
```
<script type="text/javascript">

  const formJSON_xzHb1glj = {"name":"nullForm","settings":{"recaptcha":{"isEnabled":"true","siteKey":"CHANGEME"}}}

  //Rest of the script

</script>
```

Blog gets this
```
<script type="text/javascript">

  const formJSON_jN3vTNTo = {"components":[{"label":"Post Count","labelPosition":"top","placeholder":"","description":"","tooltip":"","prefix":"","suffix":"","widget":{"type":"input"},"customClass":"","tabindex":"","autocomplete":"","hidden":false,"hideLabel":false,"mask":false,"autofocus":false,"spellcheck":true,"disabled":false,"tableView":false,"modalEdit":false,"multiple":false,"persistent":true,"delimiter":false,"requireDecimal":false,"inputFormat":"plain","protected":false,"dbIndex":false,"encrypted":false,"redrawOn":"","clearOnHide":true,"customDefaultValue":"","calculateValue":"","calculateServer":false,"allowCalculateOverride":false,"validateOn":"change","validate":{"required":false,"customMessage":"","custom":"","customPrivate":false,"json":"","min":"","max":"","strictDateValidation":false,"multiple":false,"unique":false,"step":"any","integer":""},"errorLabel":"","key":"postCount","tags":[],"properties":{},"conditional":{"show":null,"when":null,"eq":"","json":""},"customConditional":"","logic":[],"attributes":{},"overlay":{"style":"","page":"","left":"","top":"","width":"","height":""},"type":"number","input":true,"unique":false,"refreshOn":"","showCharCount":false,"showWordCount":false,"allowMultipleMasks":false,"id":"eixs1nn","defaultValue":10},{"type":"button","label":"Submit","key":"submit","size":"md","block":false,"action":"submit","disableOnInvalid":true,"theme":"primary","input":true,"placeholder":"","prefix":"","customClass":"","suffix":"","multiple":false,"defaultValue":null,"protected":false,"unique":false,"persistent":false,"hidden":false,"clearOnHide":true,"refreshOn":"","redrawOn":"","tableView":false,"modalEdit":false,"labelPosition":"top","description":"","errorLabel":"","tooltip":"","hideLabel":false,"tabindex":"","disabled":false,"autofocus":false,"dbIndex":false,"customDefaultValue":"","calculateValue":"","calculateServer":false,"widget":{"type":"input"},"attributes":{},"validateOn":"change","validate":{"required":false,"custom":"","customPrivate":false,"strictDateValidation":false,"multiple":false,"unique":false},"conditional":{"show":null,"when":null,"eq":""},"overlay":{"style":"","left":"","top":"","width":"","height":""},"allowCalculateOverride":false,"encrypted":false,"showCharCount":false,"showWordCount":false,"properties":{},"allowMultipleMasks":false,"leftIcon":"","rightIcon":"","dataGridLabel":true,"id":"ejvlqsg"},{"type":"hidden","key":"contentType","label":"contentType","defaultValue":"blog-settings","hidden":false,"input":true}],"name":"blog-settingsForm","settings":{"recaptcha":{"isEnabled":"true","siteKey":"CHANGEME"}}}

  //Rest of the script

</script>
```

**Comment by lane711** [comment] 2022-08-23 18:17
The build script was added by another developer. I have not tested it myself, so it could have problems. This problem is still just happening in the container right? It works while editing on localhost?

**Comment by pietru2004** [comment] 2022-08-23 21:21
I tried but settings did not appear for things I mentioned before.
Also I have made log of docker build working so you can check it easily
As a side note
I not sure why it installs a fricking openssh-client and git to image
![obraz](https://user-images.githubusercontent.com/51274570/186268142-9309c3c9-f7a3-402d-8712-cd8a686e91e9.png)

Log:
[build-log.txt](https://github.com/lane711/sonicjs/files/9410695/build-log.txt)

**Comment by pietru2004** [comment] 2022-08-24 15:04
I edited script and after removing the step on screenshot above it still works the same

**Comment by pietru2004** [comment] 2022-08-25 11:26
I tried launching in docker desktop and I got an warning but still no Settings for text

I not sure is this important but I got warning that it could not load some scripts
![Zrzut ekranu 2022-08-25 132208](https://user-images.githubusercontent.com/51274570/186652282-062ecf87-4fc7-4cbd-af8d-04e4729f51ad.png)

**Comment by pietru2004** [comment] 2022-09-03 09:59
@lane711 I found problem
I did this
![obraz](https://user-images.githubusercontent.com/51274570/188265621-5b4e2a1d-614c-4e40-aa02-ccf1563be2ac.png)
![obraz](https://user-images.githubusercontent.com/51274570/188265646-86eabae5-b1cc-4d44-a73d-87682085441f.png)

I think it reloads page too fast so I think there is need to make form prevent reload

**Comment by pietru2004** [comment] 2022-09-03 10:00
Also found possible solution
https://stackoverflow.com/questions/22163220/prevent-page-reload-after-form-submit-node-no-ajax-available

**Comment by pietru2004** [comment] 2022-09-03 10:01
Basicly there is need to prevent default behaviour which is page reload

**Comment by pietru2004** [comment] 2022-09-03 11:16
I removed await as test
![obraz](https://user-images.githubusercontent.com/51274570/188267909-406ded39-f934-455f-9b41-712958c255e6.png)
and got new errors

![obraz](https://user-images.githubusercontent.com/51274570/188267897-db733135-1835-4e3c-b1c9-85344d4c77ca.png)
![obraz](https://user-images.githubusercontent.com/51274570/188267936-9a7d18f1-08c8-4b2c-8be1-7d8e44e156da.png)

**Comment by lane711** [comment] 2022-09-06 21:30
So ok to close this issue with your fix correct?

**Comment by pietru2004** [comment] 2022-09-06 21:48
yes

**Closed** 2022-09-06 21:48 UTC
